### ISSUE TITLE
Make shut as a module

### ISSUE THREAD

**Issue by Mulugruntz** [NiklasRosenstein/slap#13]
Shut cannot be run as `python -m shut` or `coverage run -m shut pkg test`

When doing so:

```shell
$> python -m shut
/...bin/python: No module named shut.__main__; 'shut' is a package and cannot be directly executed
$> coverage run -m shut pkg test --no-capture
No module named shut.__main__; 'shut' is a package and cannot be directly executed
```

This is an example of a `__main__.py` file (from pytest)

https://github.com/pytest-dev/pytest/blob/main/src/pytest/__main__.py
```python
"""The pytest entry point."""
import pytest

if __name__ == "__main__":    
    raise SystemExit(pytest.console_main())
```

**Comment by NiklasRosenstein** [comment]
Hey @Mulugruntz , should be easy to do. I might get to it later today, or you can also propose a PR if you like!

**Comment by Mulugruntz** [comment]
Hi @NiklasRosenstein 

It "seems" not too complicated except... that `Click` does not seem to be able to be called as a package? 🤔 

One way to go around it would be to use `Typer` instead / conjointly?
https://typer.tiangolo.com/tutorial/package/

Internally, it uses `Click` and can also be used with `Click`.

What's your opinion?

**Comment by NiklasRosenstein** [comment]
https://github.com/NiklasRosenstein/shut/blob/a7976abf2d9efeff5c7a9b3a3e47c4002163ed43/src/shut/__main__.py#L1-L6

Is all that's needed :) 

In v0.12.0

**Comment by Mulugruntz** [comment]
Nice! I went down the rabbit hole for hours and didn't test just calling `shut()` 😅
